name: Build, Test, Lint and Deploy to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Setup Node.js
      - name: Setup Node Enviroment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # 2. Set Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Run Lint
      - name: Run Lint
        run: npm run lint

      # 4. Run Tests
      - name: Run Tests
        run: npm run test

      # 5. Upload Report Tests
      - name: Upload Report Tests
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/

      # 6. Login to GitHub Container Registry
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
